apiVersion: apps/v1
kind: Deployment
metadata:
  name: dewa-deployment
  labels:
    app: salaar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: salaar
  template:
    metadata:
      labels:
        app: salaar
    spec:                            # 👈 Correct place for this spec
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        # envFrom:
        #   - configMapRef:
        #       name: my-config       # Your config map with env vars
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: dewa-html           # HTML content from ConfigMap


